# Generated by Django 4.2.16 on 2024-09-21 05:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, error_messages={'blank': 'Amount cannot be blank.', 'invalid': 'Enter a valid amount.', 'null': 'Amount cannot be null.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than zero.')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, error_messages={'invalid': 'Enter a valid creation date.'}),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], error_messages={'blank': 'Mode of payment cannot be blank.', 'invalid_choice': 'Enter a valid mode of payment.', 'null': 'Mode of payment cannot be null.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(error_messages={'blank': 'Payment ID cannot be blank.', 'max_length': 'Payment ID cannot exceed 255 characters.', 'null': 'Payment ID cannot be null.', 'unique': 'Payment ID must be unique.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], error_messages={'blank': 'Status cannot be blank.', 'invalid_choice': 'Enter a valid status.', 'null': 'Status cannot be null.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(error_messages={'null': 'User cannot be null.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
