# Generated by Django 4.2.16 on 2024-09-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
