# Generated by Django 5.1.1 on 2024-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
