# Generated by Django 5.1.1 on 2024-09-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_location_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_number_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
