# Generated by Django 4.2.16 on 2024-09-21 05:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('events', '0002_alter_event_available_tickets_alter_event_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, error_messages={'invalid': 'Enter a valid creation date.'}),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(error_messages={'null': 'Event cannot be null.'}, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_tickets',
            field=models.PositiveIntegerField(error_messages={'blank': 'Number of tickets cannot be blank.', 'invalid': 'Enter a valid number of tickets.', 'null': 'Number of tickets cannot be null.'}, validators=[django.core.validators.MinValueValidator(1, message='Number of tickets must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, error_messages={'invalid': 'Enter a valid payment.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked'), ('canceled', 'Canceled')], default='reserved', error_messages={'blank': 'Status cannot be blank.', 'invalid_choice': 'Enter a valid status.', 'null': 'Status cannot be null.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, error_messages={'invalid': 'Enter a valid update date.'}),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(error_messages={'null': 'User cannot be null.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
