# Generated by Django 4.2.16 on 2024-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_created_at_alter_booking_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked'), ('canceled', 'Canceled'), ('event_canceled', 'Event Canceled')], default='reserved', error_messages={'blank': 'Status cannot be blank.', 'invalid_choice': 'Enter a valid status.', 'null': 'Status cannot be null.'}, max_length=30),
        ),
    ]
